#!/bin/bash
nohup vlc $1 ':sout=#transcode{vcodec=mp2v,vb=800,scale=1,acodec=mpga,ab=128,channels=2,samplerate=44100}:duplicate{dst=rtp{sdp=rtsp://:8554/},dst=display}' ':no-sout-rtp-sap :no-sout-standard-sap :ttl=1 :sout-keep' &

